import type { Metadata } from "next";
import { Zen_Kurenaido } from "next/font/google";
import "./globals.css";

const zenKurenaido = Zen_Kurenaido({
  variable: "--font-zen-kurenaido",
  weight: "400",
  subsets: ['latin'],
  display: 'swap',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className="antialiased relative bg-background text-primary-foreground"
      >
        <div className={zenKurenaido.className}>
          <div className="relative z-10 h-svh w-svw pointer-events-none">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}